In [1]:
age= 22
print(type(age))

<class 'int'>

In [6]:
age=20
if age>=18:
  print("Adult")

Adult

In [7]:
age=16
if age>=18:
  print("eligible")
else:
  print("not eligible")

not eligible

In [8]:
marks=72
if marks>=80:
  print("A+")
elif marks>=75:
  print("A")
elif marks>=50:
  print("B")
else:
  print("C")

B

In [9]:
age=25
fare=80
if age>=18 and fare>=50:
  print("Condition Satisfied")

Condition Satisfied

In [12]:
age=25
survived=1
if age>=18:
  if survived==1:
    print("Adult Survivor")

Adult Survivor

In [15]:
ages=[12,23,34,45,56,67]
names=["Rishita","Priyamvada","Disha","Shreyali"]
mixed=[10,"python",6.7,True]
print(ages)
print(names)
print(mixed)

[12, 23, 34, 45, 56, 67]
['Rishita', 'Priyamvada', 'Disha', 'Shreyali']
[10, 'python', 6.7, True]

In [20]:
print(ages[-1])
print(names[-1])
names.append("Harshita")
print(names)

67
Shreyali
['Rishita', 'Priyamvada', 'Disha', 'Shreyali', 'Harshita']

In [35]:
num=[40,10,50,30]
print(len(num))
print(num.count(10))
print(num.index(30))
print(67 in num)
print(max(num))

4
1
3
False
50

In [39]:
print(sum(num))
num.sort()
print(num)
num.reverse()
print(num)

130
[10, 30, 40, 50]
[50, 40, 30, 10]

In [42]:
students=[
    ["Rishita",18,"CSE"],
    ["Disha",18,"CSE"],
    ["Priyamvada",19,"CSE"],
    ["Shreyali",19,"CSE"]
]
print(students)

[['Rishita', 18, 'CSE'], ['Disha', 18, 'CSE'], ['Priyamvada', 19, 'CSE'], ['Shreyali', 19, 'CSE']]

In [46]:
for i in num:
  if i>40:
    print(i,"greater than 40")
  else:
      print("less")

50 greater than 40
less
less
less

In [50]:
import pandas as pd
data={
    "Customer":["A1","A2","A3"],
    "Age":[30,35,67],
    "city":["Patna","delhi","Mumbai"],
    "Amount":[100,200,300]
}
df=pd.DataFrame(data)
print(df)
df.loc[df["Amount"]>100,["Customer","Amount"]]

  Customer  Age    city  Amount
0       A1   30   Patna     100
1       A2   35   delhi     200
2       A3   67  Mumbai     300

  Customer  Amount
1       A2     200
2       A3     300

In [52]:
df.iloc[0:3,0:4]

  Customer  Age    city  Amount
0       A1   30   Patna     100
1       A2   35   delhi     200
2       A3   67  Mumbai     300